### ISSUE TITLE
SMINI will not initialize with CT array of all zero values

### ISSUE THREAD

**Issue by robertromaine-AngelOak** [chestateegold/CmriSubroutines#1]
Submitted by Scott R.

With Node 1, I was scratching my head for a while until I came across a comment in one of Dr Chubbs manuals regarding the initialisation of the SMINI when NS = 0, i.e.  no searchlight signals:
‘No signals so hold message length at LM = 4 and branch to transmit packet’
Accordingly, I altered the coding as below

![image](https://user-images.githubusercontent.com/58518291/81818648-d3e7de80-951d-11ea-8df0-71e810e225d2.png)

It appears that the SMINI doesn’t like receiving the 6 CT bytes when NS = 0.

**Comment by chestateegold** [comment]
Bug fixed in most recent update
