### ISSUE TITLE
NS being set to the wrong value for susic nodes when there are more than 4 cards

### ISSUE THREAD

**Issue by robertromaine-AngelOak** [chestateegold/CmriSubroutines#2]
Submitted by Scott R.

I found that with Node 0 configured with  5 card sets of four, initialisation worked fine.   Also, with one card set everything was fine.  However if I only had two or three card sets of four, I noted that the ctoutputbuffer[0] was loaded with 1 instead of 2 or 3.  Four card sets or more worked OK.   I changed the getMaxiInitBytes function as below since NS is meant to be the number of card sets of four.    This issue was made obvious to me with Node 2 where I have 2 card sets of four.   I’m not sure how this would affect anything else but it did enable me to initialise the node.

![image](https://user-images.githubusercontent.com/58518291/81818761-f7ab2480-951d-11ea-8120-5ec74dcdf9bb.png)

**Comment by chestateegold** [comment]
Bug fixed in most recent update
